apiVersion: v1
kind: ConfigMap

metadata:
  name: mongodb-init-script

data:
  init-user.sh: |
    #!/bin/sh
    set -eu

    mongosh \
      --host localhost \
      --username "$MONGO_INITDB_ROOT_USERNAME" \
      --password "$MONGO_INITDB_ROOT_PASSWORD" \
      --authenticationDatabase admin \
      "$MONGO_INITDB_DATABASE" \
      --eval "
        db.createUser({
          user: '$MONGODB_APP_USERNAME',
          pwd: '$MONGODB_APP_PASSWORD',
          roles: [
            {
              role: 'readWrite',
              db: '$MONGO_INITDB_DATABASE'
            }
          ]
        })
      "